name = "HDF5Logging"
uuid = "e4e011d9-2e12-448d-a9bd-158b233f66f6"
authors = ["Tamas K. Papp <tkpapp@gmail.com>"]
version = "0.1.0"

[deps]
DocStringExtensions = "ffbed154-4ef7-542d-bbb7-c09d3a79fcae"
HDF5 = "f67ccb44-e63f-5c2f-98bd-6dc0ccc4ba2f"
Logging = "56ddb016-857b-54e1-b83d-db4d58db5568"

[compat]
julia = "1"
DocStringExtensions = "0.8"
HDF5 = "0.15"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
